apiVersion: apps/v1
kind: Deployment
metadata:
  name: pam-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pam-postgres
  template:
    metadata:
      labels:
        app: pam-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: pam
            - name: POSTGRES_USER
              value: pam
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pam-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pam-postgres-data