// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contas.sql

package db

import (
	"context"
)

const buscarContaPorUsuario = `-- name: BuscarContaPorUsuario :one
SELECT id, user_id, balance_id, criado_em FROM contas
WHERE user_id = $1
`

func (q *Queries) BuscarContaPorUsuario(ctx context.Context, userID string) (Conta, error) {
	row := q.db.QueryRow(ctx, buscarContaPorUsuario, userID)
	var i Conta
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BalanceID,
		&i.CriadoEm,
	)
	return i, err
}

const criarConta = `-- name: CriarConta :one
INSERT INTO contas (user_id, balance_id)
VALUES ($1, $2)
RETURNING id, user_id, balance_id, criado_em
`

type CriarContaParams struct {
	UserID    string
	BalanceID string
}

func (q *Queries) CriarConta(ctx context.Context, arg CriarContaParams) (Conta, error) {
	row := q.db.QueryRow(ctx, criarConta, arg.UserID, arg.BalanceID)
	var i Conta
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BalanceID,
		&i.CriadoEm,
	)
	return i, err
}
