// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conta struct {
	ID        int32
	UserID    string
	BalanceID string
	CriadoEm  pgtype.Timestamptz
}
